/*
 */
package com.kongmy.srs.modules.ui;

import com.kongmy.util.CamelCaseEncoder;

/**
 *
 * @author Kong My
 */
public class ResourceConstraintPanel extends javax.swing.JPanel {

    public interface ResourceConstraintListener {

        public void onCheckBoxStatedChanged(boolean isChecked, String resourceName, String value);

        public void onTextBoxKeyUp(String resourceName, String oldValue, String newValue);
    }

    /**
     * Creates new form ResourceContraintPanel
     */
    public ResourceConstraintPanel(String resourceName, String constraintValue, ResourceConstraintListener listener) {
        this.resourceName = resourceName;
        this.constraintValue = constraintValue;
        this.listener = listener;

        initComponents();;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxResource = new javax.swing.JCheckBox();
        tbxConstraint = new javax.swing.JTextField();

        cbxResource.setText(resourceName);
        cbxResource.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbxResourceStateChanged(evt);
            }
        });

        tbxConstraint.setText("constraint");
        tbxConstraint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbxConstraintKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(cbxResource, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxConstraint, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cbxResource, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tbxConstraint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbxConstraintKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxConstraintKeyReleased
        String newValue = CamelCaseEncoder.transform(tbxConstraint.getText());
        listener.onTextBoxKeyUp(resourceName, constraintValue, newValue);
        constraintValue = newValue;
        tbxConstraint.setText(constraintValue);
    }//GEN-LAST:event_tbxConstraintKeyReleased

    private void cbxResourceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbxResourceStateChanged
        listener.onCheckBoxStatedChanged(cbxResource.isSelected(), resourceName, constraintValue);
    }//GEN-LAST:event_cbxResourceStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxResource;
    private javax.swing.JTextField tbxConstraint;
    // End of variables declaration//GEN-END:variables
    private final String resourceName;
    private String constraintValue;
    private final ResourceConstraintListener listener;

    public void setCheckBoxState(boolean checked) {
        cbxResource.setSelected(checked);
    }

    public void setConstraintValue(String val) {
        constraintValue = val;
        tbxConstraint.setText(val);
    }

}
