/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kongmy.srs.ui;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import com.kongmy.srs.core.Requirement;
import com.kongmy.core.Application;
import com.kongmy.core.DataContext;
import com.kongmy.core.HasMenu;
import com.kongmy.srs.SrsApplication;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Kong My
 */
public class MainFrame extends javax.swing.JFrame implements PropertyChangeListener {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        requirementByModules = new HashMap<>();
        initComponents();

        Application.getInstance().getModules().values().forEach((module) -> {
            if (module instanceof HasMenu) {
                menuModules.add(((HasMenu) module).getMenu(this));
            }
        });
        Application.getInstance().getDataContext().addPropertyChangeListener(this);
        UpdateTitle();
        UpdateRequirements();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionPanel = new javax.swing.JPanel();
        lblSelectedDomainAndModule = new javax.swing.JLabel();
        tbxSelectedDomainAndModule = new javax.swing.JTextField();
        lblChange = new javax.swing.JLabel();
        btnAddFunctionalRequirement = new javax.swing.JButton();
        btnAddNonFunctionalRequirement = new javax.swing.JButton();
        moduleTabbedPane = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemNew = new javax.swing.JMenuItem();
        menuItemOpen = new javax.swing.JMenuItem();
        separatorOpen = new javax.swing.JPopupMenu.Separator();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemSaveAs = new javax.swing.JMenuItem();
        menuItemExport = new javax.swing.JMenuItem();
        menuItemClose = new javax.swing.JMenuItem();
        separatorClose = new javax.swing.JPopupMenu.Separator();
        menuItemRestart = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuProject = new javax.swing.JMenu();
        menuItemChangeProjectName = new javax.swing.JMenuItem();
        menuOntology = new javax.swing.JMenu();
        menuItemLoadOntology = new javax.swing.JMenuItem();
        menuItemModifyDomain = new javax.swing.JMenuItem();
        menuItemModifyMetrics = new javax.swing.JMenuItem();
        menuBoilerplate = new javax.swing.JMenu();
        menuItemModifyBoilerplates = new javax.swing.JMenuItem();
        menuItemImportBoilerplates = new javax.swing.JMenuItem();
        menuItemExportBoilerplates = new javax.swing.JMenuItem();
        menuModules = new javax.swing.JMenu();
        menuSettings = new javax.swing.JMenu();
        menuItemWriteConfigurationFile = new javax.swing.JMenuItem();
        menuItemWriteDefaultConfigurationFile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Software Requirement Specification Tool");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        actionPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSelectedDomainAndModule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSelectedDomainAndModule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedDomainAndModule.setText("Selected Domain and Module");

        tbxSelectedDomainAndModule.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbxSelectedDomainAndModule.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tbxSelectedDomainAndModule.setText("Subject Registration System/Login page");
        tbxSelectedDomainAndModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxSelectedDomainAndModuleMouseClicked(evt);
            }
        });

        lblChange.setForeground(new java.awt.Color(0, 0, 255));
        lblChange.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChange.setText("Click to change");
        lblChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangeMouseClicked(evt);
            }
        });

        btnAddFunctionalRequirement.setText("Add Functional Requirement");
        btnAddFunctionalRequirement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFunctionalRequirementActionPerformed(evt);
            }
        });

        btnAddNonFunctionalRequirement.setText("Add Non-Functional Requirement");
        btnAddNonFunctionalRequirement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNonFunctionalRequirementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbxSelectedDomainAndModule)
                    .addGroup(actionPanelLayout.createSequentialGroup()
                        .addComponent(lblSelectedDomainAndModule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddNonFunctionalRequirement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddFunctionalRequirement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAddFunctionalRequirement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSelectedDomainAndModule))
                    .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxSelectedDomainAndModule, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNonFunctionalRequirement))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        moduleTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        moduleTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        menuBar.setToolTipText("");
        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuFile.setText("File");

        menuItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuItemNew.setText("New");
        menuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewActionPerformed(evt);
            }
        });
        menuFile.add(menuItemNew);

        menuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuItemOpen.setText("Open");
        menuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuItemOpen);
        menuFile.add(separatorOpen);

        menuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSave.setText("Save");
        menuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSave);

        menuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemSaveAs.setText("Save as");
        menuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveAsActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSaveAs);

        menuItemExport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuItemExport.setText("Export");
        menuItemExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExportActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExport);

        menuItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        menuItemClose.setText("Close");
        menuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCloseActionPerformed(evt);
            }
        });
        menuFile.add(menuItemClose);
        menuFile.add(separatorClose);

        menuItemRestart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemRestart.setText("Restart");
        menuItemRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRestartActionPerformed(evt);
            }
        });
        menuFile.add(menuItemRestart);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        menuBar.add(menuFile);

        menuProject.setText("Project");

        menuItemChangeProjectName.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemChangeProjectName.setText("Change Project Name");
        menuItemChangeProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemChangeProjectNameActionPerformed(evt);
            }
        });
        menuProject.add(menuItemChangeProjectName);

        menuBar.add(menuProject);

        menuOntology.setText("Ontology");

        menuItemLoadOntology.setText("Load ontology file");
        menuOntology.add(menuItemLoadOntology);

        menuItemModifyDomain.setText("Modify domain");
        menuItemModifyDomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModifyDomainActionPerformed(evt);
            }
        });
        menuOntology.add(menuItemModifyDomain);

        menuItemModifyMetrics.setText("Modify quality metrics");
        menuItemModifyMetrics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModifyMetricsActionPerformed(evt);
            }
        });
        menuOntology.add(menuItemModifyMetrics);

        menuBar.add(menuOntology);

        menuBoilerplate.setText("Boilerplate");

        menuItemModifyBoilerplates.setText("Modify boilerplate templates");
        menuBoilerplate.add(menuItemModifyBoilerplates);

        menuItemImportBoilerplates.setText("Import boilerplate templates");
        menuBoilerplate.add(menuItemImportBoilerplates);

        menuItemExportBoilerplates.setText("Export boilerplate templates");
        menuItemExportBoilerplates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExportBoilerplatesActionPerformed(evt);
            }
        });
        menuBoilerplate.add(menuItemExportBoilerplates);

        menuBar.add(menuBoilerplate);

        menuModules.setText("Modules");
        menuBar.add(menuModules);

        menuSettings.setText("Settings");

        menuItemWriteConfigurationFile.setText("Write configuration file");
        menuItemWriteConfigurationFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemWriteConfigurationFileActionPerformed(evt);
            }
        });
        menuSettings.add(menuItemWriteConfigurationFile);

        menuItemWriteDefaultConfigurationFile.setText("Write default configuration file");
        menuItemWriteDefaultConfigurationFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemWriteDefaultConfigurationFileActionPerformed(evt);
            }
        });
        menuSettings.add(menuItemWriteDefaultConfigurationFile);

        menuBar.add(menuSettings);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moduleTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addComponent(actionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moduleTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbxSelectedDomainAndModuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxSelectedDomainAndModuleMouseClicked
        SelectModuleDialog dlg = new SelectModuleDialog(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_tbxSelectedDomainAndModuleMouseClicked

    private void btnAddFunctionalRequirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFunctionalRequirementActionPerformed
        AddFunctionalRequirementDialog dlg = new AddFunctionalRequirementDialog(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_btnAddFunctionalRequirementActionPerformed

    private void btnAddNonFunctionalRequirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNonFunctionalRequirementActionPerformed
        AddNonFunctionalRequirementDialog dlg = new AddNonFunctionalRequirementDialog(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_btnAddNonFunctionalRequirementActionPerformed

    private void menuItemExportBoilerplatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExportBoilerplatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemExportBoilerplatesActionPerformed

    private void menuItemModifyMetricsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModifyMetricsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemModifyMetricsActionPerformed

    private void lblChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseClicked
        SelectModuleDialog dlg = new SelectModuleDialog(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_lblChangeMouseClicked

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        dispose();
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemModifyDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModifyDomainActionPerformed
        ModifyDomainDialog dlg = new ModifyDomainDialog(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_menuItemModifyDomainActionPerformed

    private void menuItemWriteConfigurationFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemWriteConfigurationFileActionPerformed
        try {
            Application.getInstance().getConfiguration().WriteConfigurationToFile();
            JOptionPane.showMessageDialog(this,
                    "Configuration file created successfully",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Error saving configuration",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemWriteConfigurationFileActionPerformed

    private void menuItemWriteDefaultConfigurationFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemWriteDefaultConfigurationFileActionPerformed
        try {
            Application.getInstance().getConfiguration().LoadDefaultConfiguration();
            Application.getInstance().getConfiguration().WriteConfigurationToFile();
            JOptionPane.showMessageDialog(this,
                    "Configuration file created successfully",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Error saving configuration",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemWriteDefaultConfigurationFileActionPerformed

    private void menuItemRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRestartActionPerformed
        if (!Application.getInstance().getDataContext().isSaved()
                && JOptionPane.CANCEL_OPTION == HandleSaveDialog()) {
            return;
        }
        new Thread(() -> {
            SrsApplication.bootstrap().run();
        }).start();
        this.dispose();
    }//GEN-LAST:event_menuItemRestartActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (!Application.getInstance().getDataContext().isSaved()
                && JOptionPane.CANCEL_OPTION == HandleSaveDialog()) {
            return;
        }
        Application.getInstance().SaveLastOpened();
        try {
            Application.getInstance().getConfiguration().WriteConfigurationToFile();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void menuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewActionPerformed
        if (!Application.getInstance().getDataContext().isSaved()
                && JOptionPane.CANCEL_OPTION == HandleSaveDialog()) {
            return;
        }
        Application.getInstance().newDataContext();
        Application.getInstance().getDataContext().addPropertyChangeListener(this);
        UpdateTitle();
        this.UpdateRequirements();
    }//GEN-LAST:event_menuItemNewActionPerformed

    private void menuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenActionPerformed
        if (!Application.getInstance().getDataContext().isSaved()
                && JOptionPane.CANCEL_OPTION == HandleSaveDialog()) {
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        switch (fileChooser.showOpenDialog(this)) {
            case JFileChooser.APPROVE_OPTION: {
                try {
                    DataContext newDataContext = DataContext.Load(fileChooser.getSelectedFile());
                    Application.getInstance().setDataContext(newDataContext);
                    Application.getInstance().LoadData();
                    this.UpdateRequirements();
                    Application.getInstance().getDataContext().addPropertyChangeListener(this);
                    UpdateTitle();
                } catch (ClassNotFoundException | IOException ex) {
                    Logger.getLogger(MainFrame.class
                            .getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this,
                            "Error opening file", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_menuItemOpenActionPerformed

    private void menuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveActionPerformed
        DataContext dataContext = Application.getInstance().getDataContext();
        if (dataContext.isSaved()) {
            return;
        }
        if (!dataContext.hasFile()) {
            JFileChooser fileChooser = new JFileChooser();
            switch (fileChooser.showSaveDialog(this)) {
                case JFileChooser.APPROVE_OPTION:
                    dataContext.setFilePath(fileChooser.getSelectedFile().getAbsolutePath());
                    break;
                default:
                    return;
            }
        }
        try {
            dataContext.Save();
            dataContext.setSaved(true);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                    "Error saving file",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemSaveActionPerformed

    private void menuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveAsActionPerformed
        DataContext dataContext = Application.getInstance().getDataContext();
        JFileChooser fileChooser = new JFileChooser();

        switch (fileChooser.showSaveDialog(this)) {
            case JFileChooser.APPROVE_OPTION:
                dataContext.setFilePath(fileChooser.getSelectedFile().getAbsolutePath());
                break;
            default:
                return;
        }

        try {
            dataContext.Save();
            dataContext.setSaved(true);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                    "Error saving file",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemSaveAsActionPerformed

    private void menuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCloseActionPerformed
        if (!Application.getInstance().getDataContext().isSaved()
                && JOptionPane.CANCEL_OPTION == HandleSaveDialog()) {
            return;
        }
        Application.getInstance().newDataContext();
        UpdateRequirements();
        UpdateTitle();
    }//GEN-LAST:event_menuItemCloseActionPerformed

    private void menuItemExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExportActionPerformed
        String longString = Application.getInstance().getDataContext().getData().toString();

        int size = 200;
        String[] newArr = new String[(int) Math.ceil(1.0 * longString.length() / size)];
        for (int i = 0; i < newArr.length - 1;) {
            int start = i * size;
            int end = ++i * size;
            newArr[i - 1] = longString.substring(start, end);
        }
        newArr[newArr.length - 1] = longString.substring((newArr.length - 1) * size);

        JOptionPane.showMessageDialog(this, String.join("\n", newArr));
    }//GEN-LAST:event_menuItemExportActionPerformed

    private void menuItemChangeProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemChangeProjectNameActionPerformed
        String oldValue = Application.getInstance().getDataContext().getProjectName();
        Object newValue;
        while (true) {
            newValue = JOptionPane.showInputDialog(
                    rootPane,
                    "Please enter new project name",
                    "Edit Project Name",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    null,
                    oldValue);

            if (newValue == null) {
                return;
            } else if (newValue.toString().isEmpty()) {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Please enter a project name",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else if (newValue.equals(oldValue)) {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Please enter a different project name",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                Application.getInstance().getDataContext().setProjectName(newValue.toString());
                return;
            }
        }
    }//GEN-LAST:event_menuItemChangeProjectNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton btnAddFunctionalRequirement;
    private javax.swing.JButton btnAddNonFunctionalRequirement;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblSelectedDomainAndModule;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBoilerplate;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemChangeProjectName;
    private javax.swing.JMenuItem menuItemClose;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemExport;
    private javax.swing.JMenuItem menuItemExportBoilerplates;
    private javax.swing.JMenuItem menuItemImportBoilerplates;
    private javax.swing.JMenuItem menuItemLoadOntology;
    private javax.swing.JMenuItem menuItemModifyBoilerplates;
    private javax.swing.JMenuItem menuItemModifyDomain;
    private javax.swing.JMenuItem menuItemModifyMetrics;
    private javax.swing.JMenuItem menuItemNew;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemRestart;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JMenuItem menuItemSaveAs;
    private javax.swing.JMenuItem menuItemWriteConfigurationFile;
    private javax.swing.JMenuItem menuItemWriteDefaultConfigurationFile;
    private javax.swing.JMenu menuModules;
    private javax.swing.JMenu menuOntology;
    private javax.swing.JMenu menuProject;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JTabbedPane moduleTabbedPane;
    private javax.swing.JPopupMenu.Separator separatorClose;
    private javax.swing.JPopupMenu.Separator separatorOpen;
    private javax.swing.JTextField tbxSelectedDomainAndModule;
    // End of variables declaration//GEN-END:variables
    private Map<String, List<Requirement>> requirementByModules;

    private int HandleSaveDialog() {
        int result = JOptionPane.showConfirmDialog(
                this,
                "Do you want to save your document before closing?",
                "Save Document",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        switch (result) {
            case JOptionPane.YES_OPTION: {
                try {
                    DataContext dataContext = Application.getInstance().getDataContext();
                    if (!dataContext.hasFile()) {
                        JFileChooser fileChooser = new JFileChooser();
                        switch (fileChooser.showSaveDialog(this)) {
                            case JFileChooser.APPROVE_OPTION:
                                dataContext.setFilePath(fileChooser.getSelectedFile().getAbsolutePath());
                                break;
                            default:
                                return result;
                        }
                    }
                    Application.getInstance().SaveDataContext();
                    dataContext.setSaved(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class
                            .getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this,
                            "Error saving file",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        return result;
    }

    private void UpdateTitle() {
        DataContext dataContext = Application.getInstance().getDataContext();
        UpdateTitle(dataContext.getProjectName(), dataContext.isSaved());
    }

    private void UpdateTitle(String projectName, boolean isSaved) {
        this.setTitle(String.format("Software Requirement Specification Tool - %s%s",
                projectName, isSaved ? "" : "*"));
    }

    private void AddModuleTab(ModulePanel panel) {
        JScrollPane scrollPane = new JScrollPane(panel);
        scrollPane.getVerticalScrollBar().setUnitIncrement(30);
        moduleTabbedPane.addTab(panel.getModuleName(), scrollPane);
    }

    public void UpdateRequirements() {
        Map<String, List<Requirement>> requirementMap = (Map<String, List<Requirement>>) Application.getInstance()
                .getDataContext().getData().get(SrsApplication.DATA_GENERATED_REQUIREMENTS);

        if (requirementMap == null) {
            requirementByModules = new HashMap<>();
        } else {
            requirementByModules = requirementMap;
        }

        moduleTabbedPane.removeAll();
        requirementByModules.entrySet().forEach((entry) -> {
            AddModuleTab(new ModulePanel(entry.getKey(), entry.getValue()));
        });

    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        UpdateTitle();
    }

}
