/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kongmy.srs.modules.ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import kongmy.core.Application;
import kongmy.srs.SrsApplication;
import kongmy.srs.modules.AccessControlModule;
import kongmy.srs.modules.OntologyModule;

/**
 *
 * @author Kong My
 */
public class AccessControlDialog extends javax.swing.JDialog {

    /**
     * Creates new form AccessControlDialog
     */
    public AccessControlDialog(java.awt.Frame parent, boolean modal, AccessControlModule module) {
        super(parent, modal);
        this.module = module;
        this.allowedUsers = new ArrayList<>();
        this.restrictedUsers = new ArrayList<>();
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        accessControlPanel = new javax.swing.JPanel();
        allowedScrollPane = new javax.swing.JScrollPane();
        panelAllowed = new javax.swing.JPanel();
        lblAllowed = new javax.swing.JLabel();
        restrictedScrollPanel = new javax.swing.JScrollPane();
        panelRestricted = new javax.swing.JPanel();
        lblRestricted = new javax.swing.JLabel();
        actionControlPanel = new javax.swing.JPanel();
        cbxSelectedModule = new javax.swing.JComboBox();
        lblSelectedModule = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelAllowed.setLayout(new javax.swing.BoxLayout(panelAllowed, javax.swing.BoxLayout.Y_AXIS));
        allowedScrollPane.setViewportView(panelAllowed);

        lblAllowed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAllowed.setText("Allowed user");

        panelRestricted.setLayout(new javax.swing.BoxLayout(panelRestricted, javax.swing.BoxLayout.Y_AXIS));
        restrictedScrollPanel.setViewportView(panelRestricted);

        lblRestricted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestricted.setText("Restrictred user");

        javax.swing.GroupLayout accessControlPanelLayout = new javax.swing.GroupLayout(accessControlPanel);
        accessControlPanel.setLayout(accessControlPanelLayout);
        accessControlPanelLayout.setHorizontalGroup(
            accessControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accessControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accessControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAllowed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allowedScrollPane))
                .addGap(10, 10, 10)
                .addGroup(accessControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restrictedScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRestricted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        accessControlPanelLayout.setVerticalGroup(
            accessControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accessControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accessControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllowed)
                    .addComponent(lblRestricted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accessControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allowedScrollPane)
                    .addComponent(restrictedScrollPanel))
                .addContainerGap())
        );

        tabbedPane.addTab("Access Control", accessControlPanel);

        javax.swing.GroupLayout actionControlPanelLayout = new javax.swing.GroupLayout(actionControlPanel);
        actionControlPanel.setLayout(actionControlPanelLayout);
        actionControlPanelLayout.setHorizontalGroup(
            actionControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        actionControlPanelLayout.setVerticalGroup(
            actionControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Action Control", actionControlPanel);

        cbxSelectedModule.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSelectedModule.setText("Selected Module:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSelectedModule, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxSelectedModule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSelectedModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectedModule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap())
        );

        tabbedPane.getAccessibleContext().setAccessibleName("Action Control");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccessControlDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccessControlDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccessControlDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccessControlDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccessControlDialog dialog = new AccessControlDialog(new javax.swing.JFrame(), true, new AccessControlModule());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private final List<String> allowedUsers;
    private final List<String> restrictedUsers;
    private final AccessControlModule module;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accessControlPanel;
    private javax.swing.JPanel actionControlPanel;
    private javax.swing.JScrollPane allowedScrollPane;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cbxSelectedModule;
    private javax.swing.JLabel lblAllowed;
    private javax.swing.JLabel lblRestricted;
    private javax.swing.JLabel lblSelectedModule;
    private javax.swing.JPanel panelAllowed;
    private javax.swing.JPanel panelRestricted;
    private javax.swing.JScrollPane restrictedScrollPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    private void initData() {
        SrsApplication.bootstrap();
        OntologyModule ontologyModule = (OntologyModule) Application.getInstance().getModule(OntologyModule.class.getName());
        List<String> allActor = ontologyModule.getActorsFromDomain(null);
        List<String> allowedActor = ontologyModule.getActorsFromModule(null, "allowed");
        List<String> restrictedActor = new ArrayList<>(allActor);
        restrictedActor.removeAll(allowedActor);
        
        allowedActor.forEach((actor) -> {
            JCheckBox cbx = new JCheckBox(actor, true);
            cbx.addActionListener(((e)-> {
                if(cbx.isSelected()) {                    
                    panelRestricted.remove(cbx);
                    panelAllowed.add(cbx);
                }
                else {
                    panelAllowed.remove(cbx);
                    panelRestricted.add(cbx);
                }
                RefreshPanels();
            }));
            panelAllowed.add(cbx);
        });
        restrictedActor.forEach((actor) -> {
            JCheckBox cbx = new JCheckBox(actor, false);
            cbx.addActionListener(((e)-> {
                if(cbx.isSelected()) {                    
                    panelRestricted.remove(cbx);
                    panelAllowed.add(cbx);
                }
                else {
                    panelAllowed.remove(cbx);
                    panelRestricted.add(cbx);
                }
                RefreshPanels();
            }));
            panelRestricted.add(cbx);
        });
        RefreshPanels();
    }
    
    public void RefreshPanels() {
        panelAllowed.setSize(panelAllowed.getPreferredSize());
        panelRestricted.setSize(panelRestricted.getPreferredSize());
    }
}
