/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kongmy.srs.ui;

import java.util.List;
import kongmy.srs.core.Requirement;

/**
 *
 * @author Owner
 */
public class ModulePanel extends javax.swing.JPanel {

    private final String moduleName;
    private final List<Requirement> requirements;

    /**
     * Creates new form ModulePanel
     */
    public ModulePanel(String moduleName, List<Requirement> requirements) {
        initComponents();
        
        this.moduleName = moduleName;
        this.requirements = requirements;        
        
        for(int i = 0; i < requirements.size(); i++) {
            RequirementPanel panel = new RequirementPanel();
            panel.setRequirement(i + 1, requirements.get(i).toString());
            add(panel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    public String getModuleName() {
        return moduleName;
    }

    public List<Requirement> getRequirements() {
        return requirements;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
